title: Workto Jobs Portal
description: >- # this means to ignore newlines until "baseurl:"
  We’re making work automation simple and accessible for everyone.
  We design products and deliver services that help people
  be more productive at their work — one recipe at a time.
  Join our team in all around the world and help serve businesses all over the world.
baseurl: "/workato_jobs_demo/" # the subpath of your site, e.g. /blog
url: "https://ctjsctjs.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# markdown: kramdown
# theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
